# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-10 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='ezhuangtai',
            field=models.BooleanField(default=True, verbose_name='设备状态'),
        ),
    ]
