# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-28 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_yuyue_isquxiao'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuyue',
            name='jieshushijian',
            field=models.CharField(default='a', max_length=30, verbose_name='结束时间'),
        ),
    ]
