# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-10 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190610_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuyue',
            name='quxiaoshijian',
            field=models.BooleanField(default=False, verbose_name='是否到了取消时间'),
        ),
    ]
