# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_yuyue_jieshushijian'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuyue',
            name='qiandaoshijian',
            field=models.BooleanField(default=False, verbose_name='签到时间'),
        ),
    ]
