# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-10 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_yuyue_quxiaoshijian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='epic',
            field=models.ImageField(storage=myapp.models.ImageStorage(), upload_to='img'),
        ),
    ]
